name: Bitbake (kirkstone)

on:
  push:
    branches: [ "gh-actions" ]

jobs:
  build:
    strategy:
      matrix:
        machine: [qemuarm, qemuarm64, qemux86-64]
        recipe: [openjdk-8-jre, openjdk-11-jre, openjdk-17-jre]
    runs-on: ubuntu-latest
    steps:
      - name: Install software required by OpenEmbedded
        run: |
          sudo apt-get update
          sudo apt-get install gawk wget git diffstat unzip texinfo \
            gcc build-essential chrpath socat cpio python3 python3-pip \
            python3-pexpect xz-utils debianutils iputils-ping python3-git \
            python3-jinja2 libegl1-mesa libsdl1.2-dev xterm \
            python3-subunit mesa-common-dev zstd liblz4-tool
      - name: Checkout OE-Core
        uses: actions/checkout@v3
        with:
          repository: openembedded/openembedded-core
          ref: kirkstone
          path: oe-core
      - name: Checkout Bitbake
        uses: actions/checkout@v3
        with:
          repository: openembedded/bitbake
          ref: 2022-04.10-kirkstone
          path: oe-core/bitbake
      - name: Checkout sources of this project
        uses: actions/checkout@v3
        with:
          path: oe-core/meta-openjdk-temurin
      - name: Replace config of build-environment
        run: |
          cd oe-core
          source oe-init-build-env build
          mv -v ../meta-openjdk-temurin/.github/workflows/bitbake-buildenv-local.conf \
            conf/local.conf
      - name: Add layer to build-environment
        run: |
          cd oe-core
          source oe-init-build-env build
          bitbake-layers add-layer ../meta-openjdk-temurin
      - name: Restore cached sstate
        id: cache-sstate-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            oe-core/build/bitbake-sstate
          key: kirkstone-${{ matrix.machine }}-sstate
      - name: Build ${{ matrix.recipe }} with Bitbake
        run: |
          cd oe-core
          source oe-init-build-env build
          MACHINE=${{ matrix.machine }} bitbake ${{ matrix.recipe }}
      - name: Save sstate
        id: cache-sstate-save
        uses: actions/cache/save@v3
        with:
          path: |
            oe-core/build/bitbake-sstate
          key: ${{ steps.cache-sstate-restore.outputs.cache-primary-key }}
