name: Bitbake (kirkstone)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OE-Core
        uses: actions/checkout@v3
        with:
          repository: openembedded/openembedded-core
          ref: kirkstone
          path: oe-core
      - name: Checkout Bitbake
        uses: actions/checkout@v3
        with:
          repository: openembedded/bitbake
          ref: 2022-04.10-kirkstone
          path: oe-core/bitbake
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          path: oe-core/meta-openjdk-temurin
      - name: Add layer to build-environment
        run: |
          cd oe-core
          source oe-init-build-env build
          bitbake-layers add-layer ../meta-openjdk-temurin
      - name: Build OpenJDK 8 JRE with Bitbake
        run: |
          cd oe-core
          source oe-init-build-env build
          bitbake openjdk-8-jre
